apiVersion: v1
kind: Service
metadata:
  labels:
    app: smarthotels
    component: frontend
  name: frontend
spec:
  ports:
  - port: 80
    name: tcp-80
    targetPort: 8080
  - port: 443
    name: tcp-443
    targetPort: 443
  selector:
    app: smarthotels
    component: frontend
  type: LoadBalancer
  [[LoadBalancerIP]]
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
spec:
  template:
    metadata:
      labels:
        app: smarthotels
        component: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:1.11.10-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        - containerPort: 443
        lifecycle:
          preStop:
            exec:
              command: ["/usr/sbin/nginx","-s","quit"]
        volumeMounts:
        - name: config
          mountPath: /etc/nginx
        - name: certs
          mountPath: /etc/ssl/certs/
        - name: ssl-private
          mountPath: /etc/ssl/private/
      volumes:
      - name: config
        configMap:
          name: config-files
          items:
          - key: nginx-conf
            path: nginx.conf
          - key: self-signed.conf
            path: self-signed.conf
          - key: ssl-params.conf
            path: ssl-params.conf
      - name: certs
        configMap:
          name: ssl-files
          items:
          - key: dhparam.pem
            path: dhparam.pem
          - key: dev.crt
            path: dev.crt          
      - name: ssl-private
        configMap:
          name: ssl-files
          items:
          - key: dev.key
            path: dev.key